import React from 'react';

export interface EwayBillData {
  _id?: string;
  ewayBillNo: string;
  ewayBillDate: string;
  generatedBy: string;
  validFrom: string;
  validUntil: string;
  portal?: string;

  // Part A
  supplierGstin: string;
  supplierName: string;
  dispatchPlace: string;
  recipientGstin: string;
  recipientName: string;
  deliveryPlace: string;
  docNo: string;
  docDate: string;
  docType?: string;
  transactionType?: string;
  valueOfGoods: number | string;
  hsnCode?: string;
  reasonForTransportation?: string;
  transporter?: string;

  // Part B
  mode?: string;
  vehicleNo?: string;
  fromPlace?: string;
  enteredDate?: string;
  enteredBy?: string;
  cewbNo?: string;
  multiVehInfo?: string;
  partBPortal?: string;

  // Meta
  billId?: string;
  approxDistance?: number;
  status?: 'ACTIVE' | 'CANCELLED' | 'EXPIRED';
  remarks?: string;
}

interface EwayBillPrintTemplateProps {
  data: EwayBillData;
}

// Generate an SVG Barcode based on E-Way Bill Number
const BarcodeSvg: React.FC<{ value: string }> = ({ value: _value }) => {
  // Deterministic bar widths based on char codes for realistic barcode look
  const bars: number[] = [2, 1, 1, 2, 1, 3, 1, 1, 2, 2, 1, 1, 3, 1, 2, 1, 1, 2, 3, 1, 1, 2, 1, 1, 2, 3, 1, 2, 1, 1, 3, 1, 2, 1, 1, 2, 1, 3, 2, 1, 1, 2, 1, 1, 3, 2, 1, 1, 2, 3, 1, 1, 2];
  
  let x = 10;
  return (
    <svg width="220" height="42" viewBox="0 0 220 42" style={{ display: 'block', margin: '0 auto' }}>
      {bars.map((width, idx) => {
        const isBar = idx % 2 === 0;
        const currentX = x;
        x += width * 3;
        if (!isBar) return null;
        return <rect key={idx} x={currentX} y="0" width={width * 3} height="36" fill="#000000" />;
      })}
    </svg>
  );
};

export const EwayBillPrintTemplate: React.FC<EwayBillPrintTemplateProps> = ({ data }) => {
  const rawNo = (data.ewayBillNo || '5120 7062 3138').trim();
  const digitsOnly = rawNo.replace(/\s+/g, '');
  const formattedNo = rawNo.includes(' ')
    ? rawNo
    : digitsOnly.replace(/(\d{4})(\d{4})(\d{4})/, '$1 $2 $3');

  const qrData = encodeURIComponent(
    `EWB:${digitsOnly}|DATE:${data.ewayBillDate || ''}|FROM:${data.supplierGstin || ''}|TO:${data.recipientGstin || ''}|VAL:${data.valueOfGoods || ''}`
  );
  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=110x110&data=${qrData}`;

  const valGoodsNum = typeof data.valueOfGoods === 'number' 
    ? data.valueOfGoods 
    : parseFloat(String(data.valueOfGoods || 0).replace(/,/g, '')) || 0;

  return (
    <div
      className="eway-bill-print-container"
      style={{
        width: '100%',
        maxWidth: '780px',
        margin: '0 auto',
        backgroundColor: '#FFFFFF',
        color: '#000000',
        fontFamily: 'Arial, "Helvetica Neue", Helvetica, sans-serif',
        boxSizing: 'border-box',
        padding: '12px 16px',
        fontSize: '11px',
        lineHeight: 1.3,
      }}
    >
      {/* Top Header */}
      <div style={{ textAlign: 'center', marginBottom: '8px' }}>
        <h1
          style={{
            fontSize: '17px',
            fontWeight: 700,
            margin: '0 0 6px 0',
            letterSpacing: '0.02em',
          }}
        >
          e-Way Bill
        </h1>

        {/* QR Code */}
        <div style={{ display: 'inline-block', padding: '2px', border: '1px solid #d0d0d0', borderRadius: '2px' }}>
          <img
            src={qrUrl}
            alt="e-Way Bill QR"
            style={{ width: '90px', height: '90px', display: 'block' }}
          />
        </div>
      </div>

      {/* Main Container Table */}
      <table
        style={{
          width: '100%',
          borderCollapse: 'collapse',
          border: '1px solid #777777',
          marginBottom: '10px',
          fontSize: '11px',
        }}
      >
        <tbody>
          {/* Row 1: E-Way Bill No */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ width: '28%', padding: '5px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              E-Way Bill No:
            </td>
            <td style={{ padding: '5px 8px', fontWeight: 700, fontSize: '13px', letterSpacing: '0.04em' }}>
              {formattedNo}
            </td>
          </tr>

          {/* Row 2: E-Way Bill Date */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '5px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              E-Way Bill Date:
            </td>
            <td style={{ padding: '5px 8px', fontWeight: 600 }}>
              {data.ewayBillDate || '-'}
            </td>
          </tr>

          {/* Row 3: Generated By */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '5px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Generated By:
            </td>
            <td style={{ padding: '5px 8px' }}>
              {data.generatedBy || `${data.supplierGstin || ''} - ${data.supplierName || ''}`}
            </td>
          </tr>

          {/* Row 4: Valid From */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '5px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Valid From:
            </td>
            <td style={{ padding: '5px 8px' }}>
              {data.validFrom || `${data.ewayBillDate || ''} [${data.approxDistance || 100}Kms]`}
            </td>
          </tr>

          {/* Row 5: Valid Until */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '5px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Valid Until:
            </td>
            <td style={{ padding: '5px 8px', fontWeight: 600 }}>
              {data.validUntil || '-'}
            </td>
          </tr>

          {/* Row 6: Portal */}
          <tr style={{ borderBottom: '1.5px solid #555555' }}>
            <td style={{ padding: '5px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Portal:
            </td>
            <td style={{ padding: '5px 8px' }}>
              {data.portal || '1'}
            </td>
          </tr>

          {/* Part - A Header */}
          <tr style={{ backgroundColor: '#f9f9f9', borderBottom: '1px solid #777777' }}>
            <td
              colSpan={2}
              style={{
                padding: '4px 8px',
                fontWeight: 700,
                fontSize: '11.5px',
                textTransform: 'uppercase',
                borderTop: '1px solid #555555',
              }}
            >
              Part - A
            </td>
          </tr>

          {/* Part A: GSTIN of Supplier */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              GSTIN of Supplier
            </td>
            <td style={{ padding: '4px 8px', textTransform: 'uppercase' }}>
              {[data.supplierGstin, data.supplierName].filter(Boolean).join(',')}
            </td>
          </tr>

          {/* Part A: Place of Dispatch */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Place of Dispatch
            </td>
            <td style={{ padding: '4px 8px' }}>
              {data.dispatchPlace || '-'}
            </td>
          </tr>

          {/* Part A: GSTIN of Recipient */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              GSTIN of Recipient
            </td>
            <td style={{ padding: '4px 8px' }}>
              {[data.recipientGstin || 'URP', data.recipientName].filter(Boolean).join(' , ')}
            </td>
          </tr>

          {/* Part A: Place of Delivery */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Place of Delivery
            </td>
            <td style={{ padding: '4px 8px' }}>
              {data.deliveryPlace || '-'}
            </td>
          </tr>

          {/* Part A: Document No. */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Document No.
            </td>
            <td style={{ padding: '4px 8px', fontWeight: 600 }}>
              {data.docNo || '-'}
            </td>
          </tr>

          {/* Part A: Document Date */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Document Date
            </td>
            <td style={{ padding: '4px 8px' }}>
              {data.docDate || '-'}
            </td>
          </tr>

          {/* Part A: Transaction Type */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Transaction Type:
            </td>
            <td style={{ padding: '4px 8px' }}>
              {data.transactionType || 'Regular'}
            </td>
          </tr>

          {/* Part A: Value of Goods */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Value of Goods
            </td>
            <td style={{ padding: '4px 8px', fontWeight: 600 }}>
              {valGoodsNum.toLocaleString('en-IN', { maximumFractionDigits: 2 })}
            </td>
          </tr>

          {/* Part A: HSN Code */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              HSN Code
            </td>
            <td style={{ padding: '4px 8px' }}>
              {data.hsnCode || '3604 - FIREWORKS'}
            </td>
          </tr>

          {/* Part A: Reason for Transportation */}
          <tr style={{ borderBottom: '1px solid #999999' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Reason for Transportation
            </td>
            <td style={{ padding: '4px 8px' }}>
              {data.reasonForTransportation || 'Outward - Supply'}
            </td>
          </tr>

          {/* Part A: Transporter */}
          <tr style={{ borderBottom: '1.5px solid #555555' }}>
            <td style={{ padding: '4px 8px', fontWeight: 600, borderRight: '1px solid #999999' }}>
              Transporter
            </td>
            <td style={{ padding: '4px 8px' }}>
              {data.transporter || '-'}
            </td>
          </tr>

          {/* Part - B Header */}
          <tr style={{ backgroundColor: '#f9f9f9', borderBottom: '1px solid #777777' }}>
            <td
              colSpan={2}
              style={{
                padding: '4px 8px',
                fontWeight: 700,
                fontSize: '11.5px',
                textTransform: 'uppercase',
                borderTop: '1px solid #555555',
              }}
            >
              Part - B
            </td>
          </tr>
        </tbody>
      </table>

      {/* Part B Table */}
      <table
        style={{
          width: '100%',
          borderCollapse: 'collapse',
          border: '1px solid #777777',
          marginBottom: '14px',
          fontSize: '10.5px',
        }}
      >
        <thead>
          <tr style={{ backgroundColor: '#f5f5f5', borderBottom: '1px solid #777777', textAlign: 'left' }}>
            <th style={{ padding: '4px 6px', borderRight: '1px solid #999999', fontWeight: 700, width: '9%' }}>
              Mode
            </th>
            <th style={{ padding: '4px 6px', borderRight: '1px solid #999999', fontWeight: 700, width: '18%' }}>
              Vehicle / Trans Doc No & Dt.
            </th>
            <th style={{ padding: '4px 6px', borderRight: '1px solid #999999', fontWeight: 700, width: '18%' }}>
              From
            </th>
            <th style={{ padding: '4px 6px', borderRight: '1px solid #999999', fontWeight: 700, width: '18%' }}>
              Entered Date
            </th>
            <th style={{ padding: '4px 6px', borderRight: '1px solid #999999', fontWeight: 700, width: '18%' }}>
              Entered By
            </th>
            <th style={{ padding: '4px 4px', borderRight: '1px solid #999999', fontWeight: 700, width: '10%', textAlign: 'center' }}>
              CEWB No. (If any)
            </th>
            <th style={{ padding: '4px 4px', borderRight: '1px solid #999999', fontWeight: 700, width: '11%', textAlign: 'center' }}>
              Multi Veh.Info (If any)
            </th>
            <th style={{ padding: '4px 4px', fontWeight: 700, width: '6%', textAlign: 'center' }}>
              Portal
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style={{ padding: '5px 6px', borderRight: '1px solid #999999', verticalAlign: 'top' }}>
              {data.mode || 'Road'}
            </td>
            <td style={{ padding: '5px 6px', borderRight: '1px solid #999999', fontWeight: 600, verticalAlign: 'top' }}>
              {data.vehicleNo || '-'}
            </td>
            <td style={{ padding: '5px 6px', borderRight: '1px solid #999999', verticalAlign: 'top' }}>
              {data.fromPlace || '-'}
            </td>
            <td style={{ padding: '5px 6px', borderRight: '1px solid #999999', verticalAlign: 'top' }}>
              {data.enteredDate || data.ewayBillDate || '-'}
            </td>
            <td style={{ padding: '5px 6px', borderRight: '1px solid #999999', verticalAlign: 'top' }}>
              {data.enteredBy || data.supplierGstin || '-'}
            </td>
            <td style={{ padding: '5px 4px', borderRight: '1px solid #999999', textAlign: 'center', verticalAlign: 'top' }}>
              {data.cewbNo || '-'}
            </td>
            <td style={{ padding: '5px 4px', borderRight: '1px solid #999999', textAlign: 'center', verticalAlign: 'top' }}>
              {data.multiVehInfo || '-'}
            </td>
            <td style={{ padding: '5px 4px', textAlign: 'center', verticalAlign: 'top' }}>
              {data.partBPortal || data.portal || '1'}
            </td>
          </tr>
        </tbody>
      </table>

      {/* Bottom Barcode Section */}
      <div style={{ textAlign: 'center', margin: '12px auto 8px auto' }}>
        <BarcodeSvg value={digitsOnly} />
        <div style={{ fontSize: '10px', letterSpacing: '0.08em', marginTop: '2px', fontWeight: 600 }}>
          {digitsOnly}
        </div>
      </div>

      {/* Discrepancy Note */}
      <div
        style={{
          borderTop: '1px solid #aaaaaa',
          paddingTop: '6px',
          fontSize: '9.5px',
          color: '#333333',
          fontStyle: 'italic',
        }}
      >
        Note: If any discrepancy in information please try after sometime.
      </div>
    </div>
  );
};
